version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-facade
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: facade-service-db
    ports:
      - "3308:3306"
    volumes:
      - facade_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  facade_mysql_data:
